spring.application.name=Herramientas

spring.datasource.url=jdbc:mysql://localhost:3306/herramientas?createDatabaseIfNotExist=true
spring.datasource.username=User
spring.datasource.password=Alvarado503.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true